language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libboost-all-dev libexpat1-dev liburiparser-dev
script: cmake . && make && make install
